### ISSUE TITLE
The Daily Note Command doesn't seem to open the Daily Note

### ISSUE THREAD

**Issue by gwenf** [tallguyjenks/Obsidian-Workflow#1]
I'm trying to figure out why this won't work. They other two commands work fine as they are.

**Comment by tallguyjenks** [comment]
I think its the keybinding, in settings look under **hotkeys** and find `open today's note` and set that to `⌘T` not`⌘⇧T`

**Comment by gwenf** [comment]
I didn't realize that I had to enable the daily notes plugin first:

<img width="1169" alt="Screen Shot 2020-11-09 at 3 49 59 PM" src="https://user-images.githubusercontent.com/10039233/98594863-3b9b9e00-22a3-11eb-80b2-f2cf7ab36e26.png">

Then I did what you said above and added the `command` + `t` hotkey for opening the daily note.

I also had to change the delay in Alfred from .2 seconds to 2 seconds because my computer is old and slow :)

**Comment by tallguyjenks** [comment]
woot! 🙌🏻
